// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
    "SignInForm":{
      "signIn": "Sign in",
      "password": "Password",
      "email": "Email",
      "registration": "Registration",
      "resetPassword": "Reset password"
    },

    "RegistrationForm":{
      "register": "Register",
      "title": "Registration",
      "email": "Enter your email",
      "password": "Enter your password",
      "langlevel": "Choose required czech level",
      "origlang": "Select language to translate words"
    },

    "LocaleSwitcher": {
      "label": "Change language",
      "locale": "{locale, select, cs {cs Čeština} en {🇺🇸 English} ru {ru Русский} other {Unknown}}"
    },

    "Navigation": {
      "words": "Words",
      "topics": "Topics",
      "rules": "Rules",
      "exercises": "Exercises",
      "tags": "Tags"
    },

    "Words": {
      "dictionary": "Word dictionary",
      "export": "Export",
      "enterCzechWord": "Write word in czech language",
      "createWord": "Add word",
      "searchWord": "Search"
    },

    "Word": {
      "dictionary": "Word dictionary",
      "export": "Export",
      "loading": "Loading",
      "noTranslations": "No translations",
      "topics": "Topics",
      "tags": "Tags",
      "languageLevel": "Language level",
      "examples": "Examples",
      "original": "Original",
      "translated": "Translated",
      "edit": "Edit",
      "wordForms": "Word forms"
    },

    "WordForms": {
      "Number": "Number",
      "Negation": "Negation",
      "Gender": "Gender",
      "Aspect": "Aspect",
      "Type": "Type (mode)",
      "Person": "Person",
      "Reset": "Reset",
      "Degree": "Degree",
      "Case": "Case"
    }
  };
export default messages;